services:
  - type: web
    runtime: python
    name: forex-trading-bot
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: RENDER_EXTERNAL_URL
        value: https://forex-trading-bot-h1z9.onrender.com
